// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tech.Data;

#nullable disable

namespace Tech.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "bec71b05-8f3d-4849-88bb-0e8d518d2de8",
                            Name = "Funcionário",
                            NormalizedName = "FUNCIONÁRIO"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("perfil_regra", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usuario_token", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("usuario_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuario_perfil", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tech.Models.Banca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("banca");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Avança SP",
                            Tipo = "medio"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Avança SP",
                            Tipo = "superior"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Instituto Consulplan",
                            Tipo = "medio"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Instituto Consulplan",
                            Tipo = "superior"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "UFRR",
                            Tipo = "superior"
                        });
                });

            modelBuilder.Entity("Tech.Models.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Acerto")
                        .HasColumnType("longtext");

                    b.Property<bool>("Acertou")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AlternativaSelecionada")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("DataResposta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("QuestionarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("historico");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acerto = " ",
                            Acertou = false,
                            AlternativaSelecionada = "A",
                            DataResposta = new DateTime(2025, 5, 20, 20, 13, 23, 693, DateTimeKind.Local).AddTicks(5581),
                            Erro = " ",
                            QuestaoId = 1,
                            QuestionarioId = 1,
                            UsuarioId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005"
                        });
                });

            modelBuilder.Entity("Tech.Models.Questionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BancaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300000)
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BancaId");

                    b.ToTable("questionario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BancaId = 2,
                            Nome = "Questionario"
                        });
                });

            modelBuilder.Entity("Tech.Models.Questoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AlternativaA")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AlternativaB")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AlternativaC")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AlternativaCorreta")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AlternativaD")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("AlternativaE")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Questao")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<int>("QuestionarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionarioId");

                    b.ToTable("questoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlternativaA = "Ctrl + Delete",
                            AlternativaB = "Ctrl + Backspace",
                            AlternativaC = "Ctrl + Função",
                            AlternativaCorreta = "A",
                            AlternativaD = "Ctrl + End",
                            AlternativaE = "Ctrl + -",
                            Questao = "O uso de teclas de atalho no Microsoft Word proporciona maior agilidade na edição e formatação de textos, permitindo que o usuário execute comandos de forma rápida e eficiente. Considerando esse recurso, qual combinação de teclas deve ser utilizada para excluir a palavra localizada à direita do cursor?",
                            QuestionarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            AlternativaA = "Uma ferramenta para ajustar a orientação da página.",
                            AlternativaB = "Um recurso para selecionar o tipo de papel a ser utilizado.",
                            AlternativaC = "Um controle deslizante de zoom no documento, permitindo ampliar ou reduzir a visualização para facilitar a leitura de textos pequenos.",
                            AlternativaCorreta = "C",
                            AlternativaD = "Uma opção para configurar margens personalizadas.",
                            AlternativaE = "Um contador para acompanhar a evolução da impressão.",
                            Imagem = "../img/QuestaoEM.png",
                            Questao = "Antes de realizar a impressão de um documento no Microsoft Word, o usuário tem a possibilidade de visualizar o conteúdo e definir quais páginas serão impressas, ajustando configurações conforme necessário. Considerando os recursos disponíveis na tela de impressão, a imagem apresentada refere-se a:",
                            QuestionarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            AlternativaA = "Dir",
                            AlternativaB = "Log",
                            AlternativaC = "Conf",
                            AlternativaCorreta = "A",
                            AlternativaD = "List",
                            AlternativaE = "Inf",
                            Questao = "No que diz respeito a interação com programas e aplicativos do Windows 7, o Prompt de Comando no Windows 7 é uma interface de linha de comando que possibilita a execução de diversas operações no sistema, oferecendo maior controle sobre arquivos e diretórios. Para exibir todos os arquivos e pastas contidos em um diretório específico, qual comando deve ser utilizado no programa: ",
                            QuestionarioId = 1
                        },
                        new
                        {
                            Id = 4,
                            AlternativaA = "Xamarin",
                            AlternativaB = "Mono",
                            AlternativaC = "UWP",
                            AlternativaCorreta = "D",
                            AlternativaD = ".NET 5+",
                            AlternativaE = ".Net Framework",
                            Questao = "Indique a alternativa que apresenta a implementação do .NET mais adequada para criação de aplicativos multiplataforma, que executam em Windows, Linux e macOS.",
                            QuestionarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            AlternativaA = "Reinicializar seu computador para que o sistema operacional realize a reinstalação automaticamente.",
                            AlternativaB = "Acessar “Gerenciador de dispositivos”, localizar seu dispositivo e atualizá-lo.",
                            AlternativaC = "Pesquisar na web um driver do fabricante do dispositivo.",
                            AlternativaCorreta = "B",
                            AlternativaD = "Entrar em contato com o suporte da Microsoft e solicitar o driver do dispositivo.",
                            AlternativaE = "Ativar a função de mouse virtual.",
                            Questao = "Um funcionário de uma empresa relata ao departamento de TI que o mouse de seu computador Windows não está funcionando, mesmo tendo testado outros periféricos do mesmo tipo e religar seu computador. Um dos técnicos de suporte instrui o funcionário a atualizar o driver do dispositivo manualmente. Qual das seguintes ações apresenta um método mais eficiente da resolução do problema?",
                            QuestionarioId = 1
                        },
                        new
                        {
                            Id = 6,
                            AlternativaA = "Inserir um filtro na coluna de Presença pelo menu 'Dados'; filtrar pela palavra “Ausente”; e aplicar manualmente a cor desejada nas células. ",
                            AlternativaB = "Selecionar toda a tabela; acessar o menu “Fórmulas”; criar uma nova regra condicional personalizada baseada no texto “Ausente”; e configurar as opções de preenchimento. ",
                            AlternativaC = "Selecionar toda a coluna da tabela; acessar o menu “Página Inicial”; clicar em “Classificar e Filtrar”; e configurar uma nova regra para destacar células onde o texto seja 'Ausente' ",
                            AlternativaCorreta = "A",
                            AlternativaD = "Acessar o menu “Exibir”; ativar o modo de Visualização de Fórmulas; selecionar a coluna Data; e aplicar uma formatação condicional baseada na fórmula =B2='Ausente', ajustando a formatação de acordo com a necessidade. ",
                            AlternativaE = "Selecionar as células da coluna de presença; acessar o menu “Página Inicial”; clicar em “Formatação Condicional”; escolher “Realçar Regras das Células”; selecionar a opção “É Igual a”; digitar “Ausente” no campo de texto; e definir a formatação desejada.",
                            Questao = "No setor de planejamento estratégico da Câmara Municipal de Araraquara, um funcionário recebeu uma planilha no Excel M365 com dados de frequência de comparecimento de vereadores em sessões plenárias, organizados por nome, data e presença (indicado com “Presente” ou “Ausente”). O objetivo é destacar, em cada linha da planilha, as datas em que os vereadores estiveram ausentes. Para isso, foi solicitado o uso do recurso de formatação condicional no Excel M365. Assinale a afirmativa, a seguir, que descreve corretamente como configurar a formatação condicional para destacar as datas cujo valor da célula na coluna de presença seja igual a “Ausente”.",
                            QuestionarioId = 1
                        },
                        new
                        {
                            Id = 7,
                            AlternativaA = "Converter manualmente a data de admissão em cada carta gerada, usando a opção “Pesquisar e Substituir” para filtrar os servidores com mais de cinco anos, antes de efetivamente concluir a mala direta.",
                            AlternativaB = "Configurar a mala direta para que todos os destinatários recebam a mesma mensagem de forma genérica e, posteriormente, ocultar o texto manualmente nas cartas geradas para aqueles com menos de cinco anos de serviço.",
                            AlternativaC = "Ajustar a fonte da mensagem no próprio corpo do documento Word para cor branca sempre que o servidor tiver menos de cinco anos de serviço, tornando a mensagem invisível para esse grupo sem o uso de regras ou campos adicionais.",
                            AlternativaCorreta = "E",
                            AlternativaD = "Inserir um campo IF no Word que compara diretamente a data de admissão do servidor ao dia atual, usando a função interna do Word para subtrair datas e avaliar se o resultado é maior que cinco anos, sem necessidade de cálculos prévios.",
                            AlternativaE = "Criar, no Excel, uma coluna que calcule se o servidor já completou cinco anos de serviço (por exemplo, gerando “Sim” ou “Não”), e então usar o campo IF (Se...Então...Senão) no Word para inserir a mensagem somente quando o valor dessa coluna for “Sim”.",
                            Questao = "O setor de Recursos Humanos da Câmara Municipal de Araraquara precisa enviar uma notificação individualizada a todos os servidores sobre uma nova política de benefícios. Para agilizar o processo, optou-se pelo uso da Mala Direta do Microsoft Word (versão 365), vinculada a uma planilha do Excel que contém os dados de cada servidor: nome, endereço, cargo, e-mail e data de admissão. Além do texto principal, deseja-se que seja exibida automaticamente, no corpo da carta, uma mensagem adicional apenas para os servidores que têm mais de cinco anos de serviço, calculados com base na data de admissão. Considerando a necessidade de inserir essa mensagem condicional na correspondência personalizada, assinale a afirmativa que descreve corretamente como configurar a Regra “Se...Então...Senão” (If...Then...Else) no Word 365, a fim de exibir a mensagem somente para os servidores com mais de cinco anos de serviço. ",
                            QuestionarioId = 1
                        },
                        new
                        {
                            Id = 8,
                            AlternativaA = "Gráfico de Pizza.",
                            AlternativaB = "Gráfico de Linhas.",
                            AlternativaC = "Gráfico de Radar.",
                            AlternativaCorreta = "B",
                            AlternativaD = "Gráfico de Árvore (Treemap).",
                            AlternativaE = "Gráfico de Histograma.",
                            Imagem = "../img/QuestaoES.png",
                            Questao = "Os gráficos são recursos visuais fundamentais no Microsoft Excel para representar e interpretar dados de maneira clara e objetiva. Entre os diversos tipos disponíveis, há um modelo em que as categorias são distribuídas de forma uniforme no eixo horizontal, enquanto os valores são organizados igualmente no eixo vertical. Esse tipo de gráfico é ideal para demonstrar a evolução de informações contínuas ao longo do tempo, facilitando a visualização de tendências em períodos regulares, como meses, trimestres ou anos fiscais.Com base nessa descrição, e na imagem a seguir, assinale a alternativa que identifica corretamente o tipo de gráfico mencionado:",
                            QuestionarioId = 1
                        },
                        new
                        {
                            Id = 9,
                            AlternativaA = "Starvation.",
                            AlternativaB = "Host.",
                            AlternativaC = "Livelock.",
                            AlternativaCorreta = "A",
                            AlternativaD = "Deadlock.",
                            AlternativaE = "Checkpoint.",
                            Questao = "O Sistema Operacional (SO) precisa lidar constantemente com requisições por recursos, dependendo de um algoritmo para decidir qual processo consegue determinado recurso e quando. Considere a seguinte situação na qual muitos processos querem imprimir um documento: suponha que o algoritmo implementado no SO para decidir como alocar a impressora, cede esse dispositivo ao processo com o menor arquivo a ser impresso. Tal algoritmo busca maximizar o atendimento rápido a processos com pequenas tarefas a serem executadas. Ocorre que existem muitos processos requisitando a impressora, sendo que um desses processos possui um arquivo grande. Assim, a cada instante no qual a impressora está livre, o algoritmo do SO a disponibiliza para o próximo processo com arquivo pequeno para imprimir, de modo que o processo com arquivo grande é preterido indefinidamente, embora não esteja bloqueado. Essa situação leva o processo com arquivo grande a ser impresso a condição de _________.",
                            QuestionarioId = 1
                        },
                        new
                        {
                            Id = 10,
                            AlternativaA = "(1) (2) (2) (2).",
                            AlternativaB = "(2) (1) (1) (2).",
                            AlternativaC = "(1) (1) (2) (2).",
                            AlternativaCorreta = "D",
                            AlternativaD = "(2) (2) (1) (2).",
                            AlternativaE = "(2) (1) (2) (1).",
                            Questao = "A lista abaixo apresenta duas tecnologias amplamente utilizadas no contexto de servidores Web. Associe elas às suas características de acordo com sua numeração.<br>1. Apache Webserver.<br>2. Nginx<br>( ) Utiliza um modelo orientado em eventos, no qual um único processo principal coordena vários processos trabalhadores, cada um com um único thread.<br>( ) Sua configuração é orientada a blocos. <br>( ) Utiliza um modelo baseado em processos/threads, em que cada conexão é gerenciada por um processo ou thread distinto.<br>( ) É nativamente mais estendido por módulos. <br>A sequência CORRETA dessa associação é: ",
                            QuestionarioId = 1
                        });
                });

            modelBuilder.Entity("Tech.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39fd4d92-0c5b-4de5-a309-89ddceb51775",
                            Email = "bruuna.oliveiraa1@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/IconeMasculino.png",
                            LockoutEnabled = true,
                            Nome = "Bruna Maria Lopes de Oliveira",
                            NormalizedEmail = "BRUUNA.OLIVEIRAA1@GMAIL.COM",
                            NormalizedUserName = "BRUNALOPES",
                            PasswordHash = "AQAAAAIAAYagAAAAEGgt8SmlaMYSpx5IXavo+aRKuljmVCojeawjcGWuY+jk0XH7MRl/UKwDOUtxYuqi9A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e265f229-2d71-458d-bae0-57efab605b88",
                            TwoFactorEnabled = false,
                            UserName = "BrunaLopes"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tech.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tech.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tech.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tech.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tech.Models.Historico", b =>
                {
                    b.HasOne("Tech.Models.Questoes", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tech.Models.Questionario", "Questionario")
                        .WithMany()
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tech.Models.Usuario", "Usuario")
                        .WithMany("Historicos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");

                    b.Navigation("Questionario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tech.Models.Questionario", b =>
                {
                    b.HasOne("Tech.Models.Banca", "Banca")
                        .WithMany("Questionarios")
                        .HasForeignKey("BancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banca");
                });

            modelBuilder.Entity("Tech.Models.Questoes", b =>
                {
                    b.HasOne("Tech.Models.Questionario", "Questionario")
                        .WithMany("Questoes")
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("Tech.Models.Banca", b =>
                {
                    b.Navigation("Questionarios");
                });

            modelBuilder.Entity("Tech.Models.Questionario", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("Tech.Models.Usuario", b =>
                {
                    b.Navigation("Historicos");
                });
#pragma warning restore 612, 618
        }
    }
}
